name: workflow for env and run-name
run-name: creating sample workflow for run-name

on:
 push:
  branches:
    - main
env:
  name: "Angel-suchita"
  APP: "elearn"
  managed_by: "Suchita"  
  
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout ${{env.name}}
         uses: actions/checkout@v6.0.2
         
       - name: build ${{env.name}}
         run: echo " Building app $ APP managed by $managed_by" 
         
          
          
     
    
